// Generated by gencpp from file beginner_tutorials/Distancia.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_DISTANCIA_H
#define BEGINNER_TUTORIALS_MESSAGE_DISTANCIA_H

#include <ros/service_traits.h>


#include <beginner_tutorials/DistanciaRequest.h>
#include <beginner_tutorials/DistanciaResponse.h>


namespace beginner_tutorials
{

struct Distancia
{

typedef DistanciaRequest Request;
typedef DistanciaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Distancia
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::Distancia > {
  static const char* value()
  {
    return "0ceadde973f9e22e63aec3f9a9e20a83";
  }

  static const char* value(const ::beginner_tutorials::Distancia&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::Distancia > {
  static const char* value()
  {
    return "beginner_tutorials/Distancia";
  }

  static const char* value(const ::beginner_tutorials::Distancia&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::DistanciaRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::Distancia >
template<>
struct MD5Sum< ::beginner_tutorials::DistanciaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Distancia >::value();
  }
  static const char* value(const ::beginner_tutorials::DistanciaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::DistanciaRequest> should match
// service_traits::DataType< ::beginner_tutorials::Distancia >
template<>
struct DataType< ::beginner_tutorials::DistanciaRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Distancia >::value();
  }
  static const char* value(const ::beginner_tutorials::DistanciaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::DistanciaResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::Distancia >
template<>
struct MD5Sum< ::beginner_tutorials::DistanciaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Distancia >::value();
  }
  static const char* value(const ::beginner_tutorials::DistanciaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::DistanciaResponse> should match
// service_traits::DataType< ::beginner_tutorials::Distancia >
template<>
struct DataType< ::beginner_tutorials::DistanciaResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Distancia >::value();
  }
  static const char* value(const ::beginner_tutorials::DistanciaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_DISTANCIA_H
